# Site settings
title:          Codenote
description:    "Заметки и алгоритмы"
url:            "https://kubrikk.github.io/codenote"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         kubrikk
  url:          "https://kubrikk.github.io/codenote"
  email:        k1306969@gmail.com

# Build settings
markdown:       kramdown
kramdown:
    math_engine: katex
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

remote_theme: chesterhow/tale

permalink:    /:year-:month-:day/:title
paginate:     5

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-toc
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale
